services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5050:5050"
    environment:
      - BACKEND_URL=http://192.168.87.30:8071
      - BACKEND_SRC=/backend-src
      - ENV=dev
      - GIT_DISCOVERY_ACROSS_FILESYSTEM=1
    volumes:
      - ./frontend:/app
      - ./backend/src:/backend-src:ro